### PR TITLE
Version control of auto-generated code from rpc.proto

### PR DESCRIPTION
**Pull request by utam0k**
:wave: Hi, team.
Is there any reason to ignore this file? Youki team has trouble that `rust-criu` often got compiles failed because of lack of this file for some reason.

### CODE REVIEW

**Comment by utam0k** [comment]
@adrianreber May I ask you to review this one?

**Comment by utam0k** [comment]
@adrianreber May I ask you to review it?

**Review by rst0git — APPROVED** [review]
LGTM

**Comment by utam0k** [comment]
@adrianreber Hi, thanks for your review. Are you planning to publish a new version?

**Comment by adrianreber** [comment]
> @adrianreber Hi, thanks for your review. Are you planning to publish a new version?

See release v0.4.0

**Pull request merged**
