### PR TITLE
Another try to make rust-criu work with crates.io

### PR DESCRIPTION
**Pull request by adrianreber**

### CODE REVIEW

**Comment by adrianreber** [comment]
@rst0git The previous change did not work with crates.io. Maybe this approach is better.

**Comment by adrianreber** [comment]
No, still not perfect.

**Comment by adrianreber** [comment]
@rst0git PTAL, this seems to be finally something that makes sense and is accepted by crates.io.

**Comment by rst0git** [comment]
Hmm, the test seems to fail when building locally without `GENERATE_PROTOBUF=1 GENERATE_TEST_PROCESS=1`:
```bash
$ GENERATE_PROTOBUF=1 GENERATE_TEST_PROCESS=1 cargo build 
$ sudo ./target/debug/rust-criu-test `which criu`
Version from CRIU found in $PATH: 31800
Version from /usr/sbin/criu: 31800
Dumping PID 375151
Restoring PID 375151
Cleaning up

$ sudo git clean -dfx
$ cargo build
$ sudo ./target/debug/rust-criu-test `which criu`
Version from CRIU found in $PATH: 31800
Version from /usr/sbin/criu: 31800
thread 'main' panicked at 'Starting test process failed (Os {
    code: 2,
    kind: NotFound,
    message: "No such file or directory",
})', src/bin.rs:34:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by adrianreber** [comment]
That is expected as the test process is not created by build.rs without the right environment variable.

To upload something to crates.io nothing should be created outside of OUT_DIR.

Should I add a line to the readme about how to test?

**Comment by rst0git** [comment]
> Should I add a line to the readme about how to test?

Yes, it might be useful for future reference.

**Pull request merged**
